{
	"version": 1522017218,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/personagem-sheet0.png",
		"images/personagem-sheet1.png",
		"images/chão-sheet0.png",
		"images/armario-sheet0.png",
		"images/sprite-sheet0.png",
		"images/agenda-sheet0.png",
		"images/telefone-sheet0.png",
		"images/cadeira-sheet0.png",
		"images/radio-sheet0.png",
		"images/radio-sheet1.png",
		"images/radio-sheet2.png",
		"images/aperteespao-sheet0.png",
		"images/paredeinvisivel-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/painel-sheet0.png",
		"images/painel-sheet1.png",
		"images/painel-sheet2.png",
		"media/[1 hour] super mario game over (trap remix).ogg",
		"media/bola_de_fogo_-_atoladinha_mp3cut.net.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}